version: '3.3'
services:
  db:
    image: postgres:11-alpine
    container_name: geofishing_db
    ports:
      - "5437:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=internship
      - POSTGRES_PASSWORD=internship
      - POSTGRES_DB=internship